### ISSUE TITLE
FIX => Production navigation

### ISSUE THREAD

**Issue by MatthiasWanner** [MatthiasWanner/scrum_poker-front_vue#35]
In production, netlify don't found page if we refresh

- [x] Create netlify.toml file at the root of the project
```toml
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
```
